---
- name: libreoffice role
  tags:
    - libreoffice
  block:

  # flatpak
  - name: Flatpak state {{ libreoffice_flatpak_state }}
    become: true
    community.general.flatpak:
      name: org.libreoffice.LibreOffice
      method: system
      state: "{{ libreoffice_flatpak_state }}"

  # apt
  - name: Apt state {{ libreoffice_apt_state }}
    become: true
    ansible.builtin.apt:
      state: "{{ libreoffice_apt_state }}"
      name: 
      - libreoffice
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-impress
      - libreoffice-base
      - libreoffice-draw
      - libreoffice-math